### ISSUE TITLE
Encountered an unknown error when doing 'sudo tap update'

### ISSUE THREAD

**Issue by dotexe1337** [hwittenborn/tap#40]
The system is Debian Sid on amd64

`michael@dimensional-rift:~/Sources/tap$ sudo tap update
>> Reading APT cache...  
>> Updating APT cache...  
>> Updating MPR cache...  
>> Updating other cache files...  

>> Encountered an unknown error.
>> Full traceback at '/tmp/tap-w9p8e08e'.
`

/tmp/tap-w9p8e08e:
`michael@dimensional-rift:~/Sources/tap$ sudo cat /tmp/tap-w9p8e08e 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tap/main.py", line 72, in main
    _main()
  File "/usr/lib/python3/dist-packages/tap/main.py", line 67, in _main
    operations[cfg.operation]()
  File "/usr/lib/python3/dist-packages/tap/update.py", line 66, in update
    _upgrade()
  File "/usr/lib/python3/dist-packages/tap/upgrade.py", line 28, in _upgrade
    rpc_data = cfg.mpr_cache.package_dicts[i.name]
KeyError: 'tap'
`

I tried re-installing tap with no luck.

**Comment by hwittenborn** [comment]
Could you send over the contents of `/var/cache/tap/mpr-cache.json`? I'm suspecting this is an issue from something on the MPR itself (though Tap should also be handling it correctly when the situation arises).

**Comment by dotexe1337** [comment]
`/var/cache/tap/mpr-cache.json` just has 2 lines with an open bracket on one and close bracket on the other. No data in there.

**Comment by dotexe1337** [comment]
Awesome. Thank you! :)

**Comment by dotexe1337** [comment]
Hi, I just tried tap again and it works now! So I guess whichever changes were made in the last few hours have fixed it.
```
michael@dimensional-rift:~$ sudo tap search discord
>> Reading APT cache...  
>> Reading MPR cache...  
>> Reading package descriptions...  
>> Generating results...  
discord/0.0.16-6 [MPR]
  Chat for Communities and Friends

discord-canary/0.0.131-1 [MPR]
  Chat for Communities and Friends

discord-ptb/0.0.26-2 [MPR]
  Chat for Communities and Friends. PTB branch.

libdatetime-calendar-discordian-perl/1.0-2.1 [APT]
  Perl extension for the Discordian Calendar

php-symfony-discord-notifier/5.4.2+dfsg-3 [APT]
  Symfony Discord Notifier Bridge

purple-discord/0.9.2021.11.24.git.de899b3-1 [APT]
  Discord messaging service plugin for libpurple

ruby-discordrb-webhooks/3.4.2-2 [APT]
  webhook client for discordrb

samblaster/0.1.26-3 [APT]
  marks duplicates, extracts discordant/split reads
```

/var/cache/tap/mpr-cache.json is now full of data too! :)

**Comment by hwittenborn** [comment]
That's my bad, I should've posted that I added the fix in the MPR :o

I'm gonna keep the issue open for the time being though, because the underlying issue still needs to be fixed.

**Comment by dotexe1337** [comment]
Alright. I'm just happy that it works now for me :)
